#Contenedores configuración
services:
  #incident-api:
   # image: docker pull melaniegng/incident-api:e4fea255f3302076a358927678fd63a50bbff2fc
   # container_name: incident-api
   # ports:
     # -"3000:3000"
    #eviroment:
      #MONGO_URL: mongodb://localhost:27017
      #PORT: 3000
      #depends_on:
        #-mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db
 
volumes:
  mongodb_volume: